### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by limeps** [tunogya/abandonai-app#14]
I subscribed to GPT-4 yesterday and used it for one day. This afternoon, I found that my account lost the subscription record and the subscription function was revoked. I was unable to resolve this issue on the website. I hope to receive a reply and a solution. Thank you.

**Comment by tunogya** [comment]
Dear valued user,

We sincerely apologize for the inconvenience you've experienced due to the error in our latest system update. Your situation has been reviewed, and it's clear that your subscription was indeed affected by this unforeseen issue.

To make amends for this inconvenience and to show our commitment to your satisfaction, we would like to offer you an additional 7 days of membership at no cost. To facilitate this extension, please send an email to tom@abandon.ai with your account details and mention of this offer. Our team will ensure that the additional membership time is promptly added to your account.

We have taken measures to prevent such errors from occurring in the future and are working diligently to enhance the quality of our service.

For any further assistance or questions, please do not hesitate to reach out to us. We appreciate your understanding and are dedicated to providing you with the best service possible.

Thank you for your continued support.

Warm regards,
The Customer Service Team, Abandon Inc.
